import type { CandidateProfile, MatchedSearchBucket, SearchBucket, SearchCategory, SearchRegion, WeeklyFreeOffer } from "./types";

export const searchCategories: SearchCategory[] = [
  ["consulting_strategy", "Consulting & Strategy"], ["finance_investment", "Finance & Investment"], ["audit_risk_transaction", "Audit, Risk & Transaction Services"], ["marketing_brand", "Marketing & Brand Management"], ["digital_growth", "Digital Marketing & Growth"], ["sales_business_development", "Sales & Business Development"], ["partnerships_sponsorship", "Partnerships & Sponsorship"], ["event_operations", "Event Management & Operations"], ["ecommerce_marketplace", "E-commerce & Marketplace"], ["product_management", "Product Management"], ["data_analytics", "Data Analytics & Business Intelligence"], ["operations_project", "Operations & Project Management"], ["supply_chain_procurement", "Supply Chain & Procurement"], ["hr_talent", "Human Resources & Talent"], ["entrepreneurship_venture", "Entrepreneurship & Venture Building"], ["sustainability_csr", "Sustainability & CSR"], ["luxury_fashion_retail", "Luxury, Fashion & Retail Management"], ["hospitality_travel", "Hospitality, Tourism & Travel"], ["sports_business", "Sports Business & Entertainment"], ["international_business_export", "International Business & Export"]
].map(([id, name]) => ({ id, name }));

const categoryById = Object.fromEntries(searchCategories.map((category) => [category.id, category])) as Record<string, SearchCategory>;
const rules = [
  ["partnerships_sponsorship", ["sponsorship", "sponsor", "partnership", "partnerships", "commercial rights"]], ["event_operations", ["event", "events", "operations", "matchday", "production"]], ["sports_business", ["sport", "sports", "club", "federation", "league", "fan engagement", "entertainment"]], ["consulting_strategy", ["consulting", "strategy", "transformation", "analyst"]], ["finance_investment", ["finance", "m&a", "investment", "private equity", "asset management"]], ["audit_risk_transaction", ["audit", "transaction", "risk", "compliance"]], ["marketing_brand", ["marketing", "brand", "product marketing", "activation"]], ["digital_growth", ["growth", "seo", "paid ads", "crm", "acquisition", "digital"]], ["sales_business_development", ["business development", "sales", "account management", "commercial development"]], ["ecommerce_marketplace", ["ecommerce", "e-commerce", "marketplace", "e-retail", "merchandising"]], ["product_management", ["product manager", "product owner", "roadmap", "user research"]], ["data_analytics", ["data", "analytics", "bi", "dashboard", "reporting"]], ["supply_chain_procurement", ["supply chain", "procurement", "logistics", "purchasing"]], ["hr_talent", ["hr", "human resources", "recruitment", "talent", "employer branding"]], ["entrepreneurship_venture", ["startup", "founder associate", "venture", "incubator"]], ["sustainability_csr", ["sustainability", "esg", "csr", "impact"]], ["luxury_fashion_retail", ["luxury", "fashion", "retail", "buying"]], ["hospitality_travel", ["hospitality", "tourism", "travel", "hotel"]], ["international_business_export", ["export", "international trade", "market entry"]]
] as Array<[string, string[]]>;

function profileText(profile: CandidateProfile) { return [...profile.targetCountries, ...profile.targetCities, ...profile.targetIndustries, ...profile.desiredRoles, ...profile.languagesSpoken, profile.idealInternshipDescription, profile.thingsToAvoid].join(" ").toLowerCase(); }
function hasAny(text: string, words: string[]) { return words.some((word) => text.includes(word)); }

export function detectSearchRegion(profile: CandidateProfile): SearchRegion {
  const text = profileText(profile);
  if (hasAny(text, ["switzerland", "geneva", "lausanne", "nyon", "zurich", "bern", "basel", "suisse"])) return "Switzerland";
  if (hasAny(text, ["australia", "sydney", "melbourne"])) return "Australia";
  if (hasAny(text, ["singapore"])) return "Singapore";
  if (hasAny(text, ["usa", "canada", "new york", "toronto"])) return "North America";
  if (hasAny(text, ["uae", "dubai", "abu dhabi", "saudi", "qatar"])) return "Middle East";
  if (hasAny(text, ["hong kong", "japan", "korea", "thailand", "indonesia", "vietnam", "malaysia"])) return "Asia-Pacific";
  if (hasAny(text, ["france", "germany", "italy", "spain", "netherlands", "uk", "belgium", "luxembourg", "austria", "nordic", "europe"])) return "Europe";
  return "International / Remote";
}

export function detectSearchCategory(profile: CandidateProfile): SearchCategory {
  const text = profileText(profile);
  const best = rules.map(([categoryId, words]) => ({ categoryId, score: words.filter((word) => text.includes(word)).length })).sort((a, b) => b.score - a.score)[0];
  return best?.score ? categoryById[best.categoryId] : categoryById.marketing_brand;
}

function offer(id: string, title: string, company: string, city: string, country: string, summary: string, score = 82): WeeklyFreeOffer {
  return { id, title, company, location: `${city}, ${country}`, country, city, url: "https://example.com/careers", source: "Cached weekly example", deadline: "Check employer page", publishedDate: "Weekly cached example", descriptionSummary: summary, requirementsSummary: "Business school student profile; requirements and dates must be verified on the employer website.", compensation: "Not live verified", languageRequirements: ["English"], rawSourceSnippet: "Cached/mock weekly example for the free search track. Not live-verified.", matchScore: score, qualityScore: Math.max(score - 5, 70), probabilityOfInterview: Math.max(score - 35, 35), whyItMatches: ["Fits the selected internship track", "Relevant business-school responsibilities", "Good example of the target market"], risks: ["Cached example, not a live-verified vacancy", "Eligibility and deadline need confirmation"], applicationAngle: "Use this as a directionally relevant example before unlocking personalized live search.", linkedinMessage: "Hi, I am exploring internships in this field and would value one tip on what junior profiles should highlight.", coverLetterHook: "I am looking for an internship where I can turn business-school training into practical project impact.", isPremium: false };
}
function bucket(id: string, categoryId: string, region: SearchRegion, displayTitle: string, shortDescription: string, whyThisBucketFits: string, offers: [WeeklyFreeOffer, WeeklyFreeOffer], fallbackBucketId = "digital_growth_international"): SearchBucket { return { id, category: categoryById[categoryId], region, displayTitle, shortDescription, whyThisBucketFits, weeklyFreeOffers: offers, fallbackBucketId }; }

export const searchBuckets: SearchBucket[] = [
  bucket("consulting_strategy_europe", "consulting_strategy", "Europe", "Consulting & Strategy in Europe", "Strategy, transformation and analyst internships across European firms.", "Your profile points toward structured problem-solving and business analysis.", [offer("weekly_consulting_1", "Strategy Analyst Intern", "Roland Berger", "Munich", "Germany", "Support market research, competitor analysis and client strategy work.", 86), offer("weekly_consulting_2", "Transformation Intern", "BearingPoint", "Amsterdam", "Netherlands", "Assist consultants with operational transformation and business cases.", 83)]),
  bucket("finance_investment_switzerland", "finance_investment", "Switzerland", "Finance & Investment in Switzerland", "Investment, asset management and corporate finance examples in Swiss markets.", "Your profile matches finance keywords and a Swiss market preference.", [offer("weekly_finance_1", "Investment Analyst Intern", "Pictet", "Geneva", "Switzerland", "Assist with investment research, portfolio material and market notes.", 87), offer("weekly_finance_2", "Corporate Finance Intern", "UBS", "Zurich", "Switzerland", "Support analysis, pitch material and transaction research.", 84)]),
  bucket("marketing_brand_europe", "marketing_brand", "Europe", "Marketing & Brand in Europe", "Brand, activation and product marketing examples for business students.", "Your inputs suggest interest in brand building, activation or marketing coordination.", [offer("weekly_brand_1", "Brand Marketing Intern", "Danone", "Paris", "France", "Support brand plans, campaign tracking and consumer insight work.", 84), offer("weekly_brand_2", "Product Marketing Intern", "Philips", "Amsterdam", "Netherlands", "Assist product marketing teams with launches and market analysis.", 82)]),
  bucket("digital_growth_international", "digital_growth", "International / Remote", "Digital Growth International", "Growth, CRM, acquisition and digital marketing examples with flexible markets.", "Your profile points toward measurable digital growth and acquisition work.", [offer("weekly_growth_1", "Growth Marketing Intern", "HubSpot", "Remote", "International / Remote", "Support acquisition experiments, reporting and campaign operations.", 85), offer("weekly_growth_2", "CRM Marketing Intern", "Canva", "Remote", "International / Remote", "Help with lifecycle campaigns, segmentation and growth reporting.", 82)]),
  bucket("sales_business_development_switzerland", "sales_business_development", "Switzerland", "Sales & Business Development in Switzerland", "Commercial development examples around Swiss B2B and international companies.", "Your profile indicates sales, account or business development interests.", [offer("weekly_sales_1", "Business Development Intern", "Logitech", "Lausanne", "Switzerland", "Support partner research, commercial tracking and go-to-market projects.", 84), offer("weekly_sales_2", "Sales Operations Intern", "Kudelski Group", "Cheseaux", "Switzerland", "Assist sales teams with pipeline reporting and account planning.", 81)]),
  bucket("partnerships_sponsorship_switzerland", "partnerships_sponsorship", "Switzerland", "Partnerships & Sponsorship in Switzerland", "Partnership, sponsorship and rights-holder examples in Swiss sport and business.", "Your profile includes sponsorship or partnership signals with a Swiss market fit.", [offer("weekly_partnerships_1", "Partnerships Intern", "UEFA", "Nyon", "Switzerland", "Support partner activation, rights delivery and event coordination.", 89), offer("weekly_partnerships_2", "Sponsorship Marketing Intern", "Infront Sports & Media", "Zug", "Switzerland", "Assist sponsor campaigns, presentations and activation tracking.", 86)]),
  bucket("event_operations_europe", "event_operations", "Europe", "Event Operations in Europe", "Event planning, production and operations examples across European organizations.", "Your profile suggests interest in events, operations or delivery work.", [offer("weekly_events_1", "Event Operations Intern", "RX Global", "London", "UK", "Support event planning, exhibitor coordination and onsite delivery.", 83), offer("weekly_events_2", "Marketing Events Intern", "Messe Frankfurt", "Frankfurt", "Germany", "Assist trade fair marketing, logistics and partner coordination.", 81)]),
  bucket("ecommerce_marketplace_europe", "ecommerce_marketplace", "Europe", "E-commerce & Marketplace in Europe", "Marketplace, merchandising and e-retail internship examples.", "Your profile points toward online retail, marketplace or merchandising work.", [offer("weekly_ecommerce_1", "Marketplace Operations Intern", "Zalando", "Berlin", "Germany", "Support assortment analysis, marketplace operations and seller reporting.", 84), offer("weekly_ecommerce_2", "E-commerce Merchandising Intern", "L'Oreal", "Paris", "France", "Assist e-retail content, merchandising and commercial performance tracking.", 82)]),
  bucket("data_analytics_europe", "data_analytics", "Europe", "Data Analytics in Europe", "Business intelligence, dashboard and reporting examples for business students.", "Your profile includes analytics, data or reporting signals.", [offer("weekly_data_1", "Business Intelligence Intern", "Booking.com", "Amsterdam", "Netherlands", "Build dashboards and support commercial performance analysis.", 85), offer("weekly_data_2", "Data Analyst Intern", "Schneider Electric", "Grenoble", "France", "Support reporting, process analysis and business insight projects.", 82)]),
  bucket("sports_business_switzerland", "sports_business", "Switzerland", "Sports Business in Switzerland", "Sports federation, club and entertainment business examples in Switzerland.", "Your profile has sport, federation, fan engagement or entertainment signals.", [offer("weekly_sports_1", "Sports Business Intern", "FIFA", "Zurich", "Switzerland", "Support business projects around competitions, stakeholders and fan initiatives.", 88), offer("weekly_sports_2", "Marketing Intern, Sports Federation", "World Triathlon", "Lausanne", "Switzerland", "Assist communications, partner coordination and event marketing work.", 86)]),
  bucket("hospitality_travel_australia", "hospitality_travel", "Australia", "Hospitality & Travel in Australia", "Hotel, tourism and travel business examples in Australia.", "Your profile points toward hospitality, travel or tourism markets in Australia.", [offer("weekly_travel_1", "Tourism Marketing Intern", "Destination NSW", "Sydney", "Australia", "Support campaign coordination and visitor market research.", 83), offer("weekly_travel_2", "Hotel Commercial Intern", "Accor", "Melbourne", "Australia", "Assist revenue, sales and guest experience projects.", 81)]),
  bucket("tech_events_marketing_singapore", "marketing_brand", "Singapore", "Tech Events & Marketing in Singapore", "Marketing, events and growth examples around Singapore's tech ecosystem.", "Your profile fits Singapore plus marketing, event or digital business signals.", [offer("weekly_sg_1", "Field Marketing Intern", "Salesforce", "Singapore", "Singapore", "Support events, campaign operations and regional marketing reporting.", 84), offer("weekly_sg_2", "Community Events Intern", "Stripe", "Singapore", "Singapore", "Assist startup community programs, event logistics and partner communication.", 82)]),
  bucket("entrepreneurship_venture_international", "entrepreneurship_venture", "International / Remote", "Entrepreneurship & Venture International", "Startup, incubator and venture building examples across flexible markets.", "Your profile suggests startup, venture, founder associate or incubator work.", [offer("weekly_venture_1", "Founder Associate Intern", "Entrepreneur First", "Remote", "International / Remote", "Support venture research, founder operations and market mapping.", 84), offer("weekly_venture_2", "Venture Building Intern", "Antler", "Remote", "International / Remote", "Assist startup scouting, business model analysis and program operations.", 82)]),
  bucket("sustainability_csr_europe", "sustainability_csr", "Europe", "Sustainability & CSR in Europe", "ESG, CSR and impact internship examples in European organizations.", "Your profile includes sustainability, ESG, CSR or impact signals.", [offer("weekly_csr_1", "Sustainability Intern", "IKEA", "Delft", "Netherlands", "Support sustainability reporting, project coordination and stakeholder material.", 84), offer("weekly_csr_2", "CSR Project Intern", "Schneider Electric Foundation", "Paris", "France", "Assist impact programs, reporting and partner coordination.", 82)]),
  bucket("luxury_fashion_retail_europe", "luxury_fashion_retail", "Europe", "Luxury, Fashion & Retail in Europe", "Luxury, fashion, retail and buying examples across European brands.", "Your profile points toward luxury, fashion, retail, merchandising or buying.", [offer("weekly_luxury_1", "Luxury Retail Marketing Intern", "LVMH", "Paris", "France", "Support retail marketing, boutique activation and performance reporting.", 86), offer("weekly_luxury_2", "Merchandising Intern", "Zara", "A Coruna", "Spain", "Assist buying teams with product analysis and market performance tracking.", 82)]),
  bucket("international_business_export_europe", "international_business_export", "Europe", "International Business & Export in Europe", "Export, market entry and international trade examples in Europe.", "Your profile suggests international trade, export or market entry interests.", [offer("weekly_export_1", "Export Business Intern", "Business France", "Paris", "France", "Support market research, export advisory and company internationalization projects.", 83), offer("weekly_export_2", "International Sales Intern", "Bosch", "Stuttgart", "Germany", "Assist export sales teams with market analysis and distributor coordination.", 81)])
];

const bucketsById = Object.fromEntries(searchBuckets.map((item) => [item.id, item])) as Record<string, SearchBucket>;
const regionSuffix: Record<SearchRegion, string> = { Switzerland: "switzerland", Europe: "europe", Australia: "australia", Singapore: "singapore", "North America": "north_america", "Middle East": "middle_east", "Asia-Pacific": "asia_pacific", "International / Remote": "international" };
function bucketIdFor(categoryId: string, region: SearchRegion) { return categoryId === "marketing_brand" && region === "Singapore" ? "tech_events_marketing_singapore" : `${categoryId}_${regionSuffix[region]}`; }
function fallbackBucket(categoryId: string, region: SearchRegion) { return searchBuckets.find((item) => item.category.id === categoryId) ?? searchBuckets.find((item) => item.region === region) ?? bucketsById.digital_growth_international; }

export function matchSearchBucket(profile: CandidateProfile): MatchedSearchBucket {
  const category = detectSearchCategory(profile);
  const region = detectSearchRegion(profile);
  const bucket = bucketsById[bucketIdFor(category.id, region)] ?? fallbackBucket(category.id, region);
  return { category, region, bucket, explanation: `${category.name} is the closest track based on the roles, industries and description you provided. ${bucket.whyThisBucketFits}` };
}
