import type { CandidateProfile, MatchedSearchBucket, SearchBucket, SearchCategory, SearchRegion, WeeklyFreeOffer } from "./types";

export const searchCategories: SearchCategory[] = [
  ["consulting_strategy", "Consulting & Strategy"], ["finance_investment", "Finance & Investment"], ["audit_risk_transaction", "Audit, Risk & Transaction Services"], ["marketing_brand", "Marketing & Brand Management"], ["digital_growth", "Digital Marketing & Growth"], ["sales_business_development", "Sales & Business Development"], ["partnerships_sponsorship", "Partnerships & Sponsorship"], ["event_operations", "Event Management & Operations"], ["ecommerce_marketplace", "E-commerce & Marketplace"], ["product_management", "Product Management"], ["data_analytics", "Data Analytics & Business Intelligence"], ["operations_project", "Operations & Project Management"], ["supply_chain_procurement", "Supply Chain & Procurement"], ["hr_talent", "Human Resources & Talent"], ["entrepreneurship_venture", "Entrepreneurship & Venture Building"], ["sustainability_csr", "Sustainability & CSR"], ["luxury_fashion_retail", "Luxury, Fashion & Retail Management"], ["hospitality_travel", "Hospitality, Tourism & Travel"], ["sports_business", "Sports Business & Entertainment"], ["international_business_export", "International Business & Export"]
].map(([id, name]) => ({ id, name }));
const categoryById = Object.fromEntries(searchCategories.map((item) => [item.id, item])) as Record<string, SearchCategory>;
const categoryByName = Object.fromEntries(searchCategories.map((item) => [item.name.toLowerCase(), item])) as Record<string, SearchCategory>;
const rules: Array<[string, string[]]> = [["partnerships_sponsorship", ["sponsorship", "sponsor", "partnership", "commercial rights"]], ["event_operations", ["event", "operations", "matchday", "production"]], ["sports_business", ["sport", "club", "federation", "league", "fan engagement"]], ["consulting_strategy", ["consulting", "strategy", "transformation", "analyst"]], ["finance_investment", ["finance", "m&a", "investment", "private equity", "asset management"]], ["audit_risk_transaction", ["audit", "transaction", "risk", "compliance"]], ["marketing_brand", ["marketing", "brand", "product marketing", "activation"]], ["digital_growth", ["growth", "seo", "paid ads", "crm", "acquisition", "digital"]], ["sales_business_development", ["business development", "sales", "account management", "commercial development"]], ["ecommerce_marketplace", ["ecommerce", "marketplace", "e-retail", "merchandising"]], ["product_management", ["product manager", "product owner", "roadmap", "user research"]], ["data_analytics", ["data", "analytics", "bi", "dashboard", "reporting"]], ["supply_chain_procurement", ["supply chain", "procurement", "logistics", "purchasing"]], ["hr_talent", ["hr", "recruitment", "talent", "employer branding"]], ["entrepreneurship_venture", ["startup", "founder associate", "venture", "incubator"]], ["sustainability_csr", ["sustainability", "esg", "csr", "impact"]], ["luxury_fashion_retail", ["luxury", "fashion", "retail", "buying"]], ["hospitality_travel", ["hospitality", "tourism", "travel", "hotel"]], ["international_business_export", ["export", "international trade", "market entry"]]];
function text(profile: CandidateProfile) { return [...profile.targetCountries, ...profile.targetCities, ...profile.targetIndustries, ...profile.desiredRoles, ...profile.languagesSpoken, profile.idealInternshipDescription, profile.thingsToAvoid].join(" ").toLowerCase(); }
function any(text: string, words: string[]) { return words.some((word) => text.includes(word)); }
function selectedCategories(profile: CandidateProfile) { return profile.desiredRoles.map((role) => categoryByName[role.toLowerCase()]).filter(Boolean); }
export function detectSearchRegion(profile: CandidateProfile): SearchRegion { const value = text(profile); if (any(value, ["switzerland", "geneva", "lausanne", "nyon", "zurich", "bern", "basel"])) return "Switzerland"; if (any(value, ["australia", "sydney", "melbourne"])) return "Australia"; if (any(value, ["singapore"])) return "Singapore"; if (any(value, ["usa", "united states", "canada", "new york", "toronto", "north america"])) return "North America"; if (any(value, ["uae", "united arab emirates", "dubai", "abu dhabi", "saudi", "qatar", "middle east"])) return "Middle East"; if (any(value, ["asia-pacific", "asia pacific", "hong kong", "japan", "korea", "thailand", "indonesia", "vietnam", "malaysia"])) return "Asia-Pacific"; if (any(value, ["international / remote", "remote", "international"])) return "International / Remote"; if (any(value, ["france", "germany", "italy", "spain", "netherlands", "united kingdom", "uk", "ireland", "belgium", "luxembourg", "austria", "denmark", "sweden", "norway", "finland", "nordic", "europe"])) return "Europe"; return "International / Remote"; }
export function detectSearchCategory(profile: CandidateProfile): SearchCategory { const selected = selectedCategories(profile); if (selected[0]) return selected[0]; const value = text(profile); const best = rules.map(([categoryId, words]) => ({ categoryId, score: words.filter((word) => value.includes(word)).length })).sort((a, b) => b.score - a.score)[0]; return best?.score ? categoryById[best.categoryId] : categoryById.marketing_brand; }
function offer(id: string, title: string, company: string, city: string, country: string, summary: string, score = 82): WeeklyFreeOffer { return { id, title, company, location: `${city}, ${country}`, country, city, url: "https://example.com/careers", source: "Cached weekly example", deadline: "Check employer page", publishedDate: "Weekly cached example", descriptionSummary: summary, requirementsSummary: "Business school student profile; requirements and dates must be verified on the employer website.", compensation: "Not live verified", languageRequirements: ["English"], rawSourceSnippet: "Cached/mock weekly example for the free search track. Not live-verified.", matchScore: score, qualityScore: score - 5, probabilityOfInterview: score - 35, whyItMatches: ["Fits the selected internship track", "Relevant business-school responsibilities", "Good example of the target market"], risks: ["Cached example, not a live-verified vacancy", "Eligibility and deadline need confirmation"], applicationAngle: "Use this as a directionally relevant example before unlocking personalized live search.", linkedinMessage: "Hi, I am exploring internships in this field and would value one tip on what junior profiles should highlight.", coverLetterHook: "I am looking for an internship where I can turn business-school training into practical project impact.", isPremium: false }; }
function bucket(id: string, categoryId: string, region: SearchRegion, title: string, companyA: string, cityA: string, countryA: string, roleA: string, companyB: string, cityB: string, countryB: string, roleB: string): SearchBucket { return { id, category: categoryById[categoryId], region, displayTitle: title, shortDescription: `${title} cached weekly examples.`, whyThisBucketFits: `This bucket matches ${categoryById[categoryId].name} interests in ${region}.`, fallbackBucketId: "digital_growth_international", weeklyFreeOffers: [offer(`${id}_1`, roleA, companyA, cityA, countryA, `Cached example for ${roleA} responsibilities in ${title}.`, 84), offer(`${id}_2`, roleB, companyB, cityB, countryB, `Cached example for ${roleB} responsibilities in ${title}.`, 82)] }; }
export const searchBuckets: SearchBucket[] = [
  bucket("consulting_strategy_europe", "consulting_strategy", "Europe", "Consulting & Strategy in Europe", "Roland Berger", "Munich", "Germany", "Strategy Analyst Intern", "BearingPoint", "Amsterdam", "Netherlands", "Transformation Intern"),
  bucket("finance_investment_switzerland", "finance_investment", "Switzerland", "Finance & Investment in Switzerland", "Pictet", "Geneva", "Switzerland", "Investment Analyst Intern", "UBS", "Zurich", "Switzerland", "Corporate Finance Intern"),
  bucket("marketing_brand_europe", "marketing_brand", "Europe", "Marketing & Brand in Europe", "Danone", "Paris", "France", "Brand Marketing Intern", "Philips", "Amsterdam", "Netherlands", "Product Marketing Intern"),
  bucket("digital_growth_international", "digital_growth", "International / Remote", "Digital Growth International", "HubSpot", "Remote", "International / Remote", "Growth Marketing Intern", "Canva", "Remote", "International / Remote", "CRM Marketing Intern"),
  bucket("sales_business_development_switzerland", "sales_business_development", "Switzerland", "Sales & Business Development in Switzerland", "Logitech", "Lausanne", "Switzerland", "Business Development Intern", "Kudelski Group", "Cheseaux", "Switzerland", "Sales Operations Intern"),
  bucket("partnerships_sponsorship_switzerland", "partnerships_sponsorship", "Switzerland", "Partnerships & Sponsorship in Switzerland", "UEFA", "Nyon", "Switzerland", "Partnerships Intern", "Infront Sports & Media", "Zug", "Switzerland", "Sponsorship Marketing Intern"),
  bucket("event_operations_europe", "event_operations", "Europe", "Event Operations in Europe", "RX Global", "London", "UK", "Event Operations Intern", "Messe Frankfurt", "Frankfurt", "Germany", "Marketing Events Intern"),
  bucket("ecommerce_marketplace_europe", "ecommerce_marketplace", "Europe", "E-commerce & Marketplace in Europe", "Zalando", "Berlin", "Germany", "Marketplace Operations Intern", "L'Oreal", "Paris", "France", "E-commerce Merchandising Intern"),
  bucket("data_analytics_europe", "data_analytics", "Europe", "Data Analytics in Europe", "Booking.com", "Amsterdam", "Netherlands", "Business Intelligence Intern", "Schneider Electric", "Grenoble", "France", "Data Analyst Intern"),
  bucket("sports_business_switzerland", "sports_business", "Switzerland", "Sports Business in Switzerland", "FIFA", "Zurich", "Switzerland", "Sports Business Intern", "World Triathlon", "Lausanne", "Switzerland", "Marketing Intern, Sports Federation"),
  bucket("hospitality_travel_australia", "hospitality_travel", "Australia", "Hospitality & Travel in Australia", "Destination NSW", "Sydney", "Australia", "Tourism Marketing Intern", "Accor", "Melbourne", "Australia", "Hotel Commercial Intern"),
  bucket("tech_events_marketing_singapore", "marketing_brand", "Singapore", "Tech Events & Marketing in Singapore", "Salesforce", "Singapore", "Singapore", "Field Marketing Intern", "Stripe", "Singapore", "Singapore", "Community Events Intern"),
  bucket("entrepreneurship_venture_international", "entrepreneurship_venture", "International / Remote", "Entrepreneurship & Venture International", "Entrepreneur First", "Remote", "International / Remote", "Founder Associate Intern", "Antler", "Remote", "International / Remote", "Venture Building Intern"),
  bucket("sustainability_csr_europe", "sustainability_csr", "Europe", "Sustainability & CSR in Europe", "IKEA", "Delft", "Netherlands", "Sustainability Intern", "Schneider Electric Foundation", "Paris", "France", "CSR Project Intern"),
  bucket("luxury_fashion_retail_europe", "luxury_fashion_retail", "Europe", "Luxury, Fashion & Retail in Europe", "LVMH", "Paris", "France", "Luxury Retail Marketing Intern", "Zara", "A Coruna", "Spain", "Merchandising Intern"),
  bucket("international_business_export_europe", "international_business_export", "Europe", "International Business & Export in Europe", "Business France", "Paris", "France", "Export Business Intern", "Bosch", "Stuttgart", "Germany", "International Sales Intern")
];
const bucketsById = Object.fromEntries(searchBuckets.map((item) => [item.id, item])) as Record<string, SearchBucket>;
const suffix: Record<SearchRegion, string> = { Switzerland: "switzerland", Europe: "europe", Australia: "australia", Singapore: "singapore", "North America": "north_america", "Middle East": "middle_east", "Asia-Pacific": "asia_pacific", "International / Remote": "international" };
function bucketIdFor(categoryId: string, region: SearchRegion) { return categoryId === "marketing_brand" && region === "Singapore" ? "tech_events_marketing_singapore" : `${categoryId}_${suffix[region]}`; }
function fallbackBucket(categoryId: string, region: SearchRegion) { return searchBuckets.find((item) => item.category.id === categoryId) ?? searchBuckets.find((item) => item.region === region) ?? bucketsById.digital_growth_international; }
export function matchSearchBucket(profile: CandidateProfile): MatchedSearchBucket { const region = detectSearchRegion(profile); const selected = selectedCategories(profile); const exact = selected.map((category) => bucketsById[bucketIdFor(category.id, region)]).find(Boolean); const category = exact?.category ?? selected[0] ?? detectSearchCategory(profile); const selectedBucket = exact ?? bucketsById[bucketIdFor(category.id, region)] ?? fallbackBucket(category.id, region); return { category, region, bucket: selectedBucket, explanation: `${category.name} is the closest track based on your selected internship track, target market and profile details. ${selectedBucket.whyThisBucketFits}` }; }
