export type FeedbackType = "relevant" | "not_relevant" | "expired" | "already_applied" | "wrong_country" | "wrong_role" | "too_senior" | "not_a_real_internship";
export type CacheReviewStatus = "pending" | "approved" | "rejected";
export type PremiumMatchType = "exact" | "close" | "broadened" | "alternative";
export type PremiumCompromiseType = "broader_industry" | "adjacent_role" | "nearby_location" | "broader_company_source";
export type PremiumSearchStatus = "not_started" | "pending_payment" | "ready_to_run" | "running" | "completed" | "failed";
export type PremiumLanguage = { language: string; level: string };
export type PremiumSearchBrief = {
  targetRoles: string[];
  rolePriority: string[];
  targetIndustries: string[];
  strictCities: string[];
  acceptableCountries: string[];
  remoteAccepted: boolean;
  languages: PremiumLanguage[];
  internshipStartDate: string;
  internshipDuration: string;
  durationStrictness: "strict" | "flexible";
  companiesAlreadyAppliedTo: string[];
  hardFilters: string[];
  softPreferences: string[];
  broadeningOrder: string[];
  profileSummary: string;
  idealInternshipDescription: string;
};
export type PremiumSearchInputs = {
  targetCountries: string[];
  targetCities: string[];
  languagesSpoken: string[];
  internshipStartDate: string;
  internshipDuration: string;
  companiesAlreadyAppliedTo: string[];
  thingsToAvoid: string;
  profileSummary: string;
  idealInternshipDescription: string;
  targetRoles?: string[];
  rolePriority?: string[];
  targetIndustries?: string[];
  strictCities?: string[];
  acceptableCountries?: string[];
  remoteAccepted?: boolean;
  languages?: PremiumLanguage[];
  durationStrictness?: "strict" | "flexible";
  hardFilters?: string[];
  softPreferences?: string[];
  broadeningOrder?: string[];
};
export type CandidateProfile = { id: string; firstName: string; email: string; cvFileUrl: string; cvText: string; targetCountries: string[]; targetCities: string[]; targetIndustries: string[]; desiredRoles: string[]; internshipStartDate: string; internshipDuration: string; languagesSpoken: string[]; minimumCompensation?: string; companiesAlreadyAppliedTo: string[]; idealInternshipDescription: string; thingsToAvoid: string; createdAt: string; premiumSearchBrief?: PremiumSearchBrief };
export type SearchCategory = { id: string; name: string };
export type SearchRegion = "Europe" | "International outside Europe" | "Switzerland" | "Australia" | "Singapore" | "North America" | "Middle East" | "Asia-Pacific" | "International / Remote";
export type InternshipOffer = { id: string; title: string; company: string; location: string; country: string; city: string; url: string; source: string; deadline: string; publishedDate: string; descriptionSummary: string; requirementsSummary: string; compensation: string; languageRequirements: string[]; rawSourceSnippet: string };
export type ScoredInternshipOffer = InternshipOffer & { matchScore: number; qualityScore: number; probabilityOfInterview: number; whyItMatches: string[]; risks: string[]; applicationAngle: string; linkedinMessage: string; coverLetterHook: string; isPremium: boolean; matchType?: PremiumMatchType; broadenedReason?: string; languageFit?: string; compromiseType?: PremiumCompromiseType; compromiseLabel?: string; whyItFits?: string };
export type WeeklyFreeOffer = ScoredInternshipOffer & { isPremium: false };
export type SearchBucket = { id: string; category: SearchCategory; region: SearchRegion; displayTitle: string; shortDescription: string; whyThisBucketFits: string; weeklyFreeOffers: WeeklyFreeOffer[]; fallbackBucketId: string };
export type MatchedSearchBucket = { category: SearchCategory; region: SearchRegion; bucket: SearchBucket; explanation: string };
export type CachedBucketOpportunity = ScoredInternshipOffer & { bucketId: string; category?: string; region?: string; isLiveVerified: boolean; verifiedAt?: string; expiresAt?: string; refreshRunId?: string; rawSources?: Array<{ url?: string; title?: string; snippet?: string }>; reviewStatus: CacheReviewStatus; reviewedAt?: string; reviewedBy?: string; createdAt?: string };
export type InternshipSearchReport = { id: string; profileId: string; status: "pending" | "completed" | "failed"; accessToken?: string; isPaid?: boolean; matchedSearch?: MatchedSearchBucket; freeOffers: ScoredInternshipOffer[]; premiumOffers: ScoredInternshipOffer[]; premiumInputs?: PremiumSearchInputs; premiumSearchStatus?: PremiumSearchStatus; premiumSearchError?: string; premiumSearchStartedAt?: string; premiumSearchCompletedAt?: string; createdAt: string; updatedAt: string; errorMessage?: string };
export type OfferFeedback = { id: string; reportId: string; offerId: string; feedbackType: FeedbackType; comment?: string; createdAt: string };
export type AdminSearchLog = { id: string; profileId: string; reportId: string; status: "completed" | "failed"; querySummary: string; errorMessage?: string; rawResponse?: string; createdAt: string };
